---
- name: "installing appache webserver"
  hosts: amazon
  become: yes
  vars_files: variables.yml
  tasks:

    - name: "installing httpd"
      yum:
        name: httpd
        state: present

    - name: "starting/enabling httpd service"
      service:
        name: httpd
        state: restarted
        enabled: true      

    - name: "creating virtualhost from virtualhost"
      template:
        src: "./virtualhost.conf.j2"
        dest: "/etc/httpd/conf.d/{{ httpd_domain }}.conf"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
 
    - name: "Creating the document root"
      file:
        path: "/var/www/html/{{ httpd_domain }}"
        state: directory
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"      
