---
- name: "installing appache webserver"
  hosts: amazon
  become: yes
  tasks:

    - name: "installing httpd"
      yum:
        name: httpd
        state: present

    - name: "starting/enabling httpd service"
      service:
        name: httpd
        state: restarted
        enabled: true      

          
